version: '3'
services:
  php-environment:
    container_name: php-apache
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: php-app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql



