version: '3'
services:
  php-environment:
    image: $IMAGE_NAME_PHP:$BUILD_NUMBER
    container_name: php-apache
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:80
  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile    
    image: $IMAGE_NAME_MYSQL:$BUILD_NUMBER
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: login_system
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      



