apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-pod1
  name: simple-pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-pod1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-pod1
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8080
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources: {}
status: {}
