apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-host
  template:
    metadata:
      labels:
        app: mysql-host
    spec:
      containers:
        - name: mysql-host
          image: mysql:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-host
              mountPath: "/var/lib/mysql"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: login_system
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
      volumes:
        - name: mysql-host
          persistentVolumeClaim:
            claimName: mysql-pvc-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-host
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
