apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv-mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Avoid accidental deletion
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-028a309bcc5dfff24 # Replace with your EBS Volume ID
    fsType: xfs # File system type
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-31-31-19
