apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: pi
          image: mysql:latest
          command:
            - /bin/sh
            - -c
            - |
              mysql -h mysql-server(mysql service name)  -uroot -p$(MYSQL_ROOT_PASSWORD) < /data/test.sql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-cred
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-init
              mountPath: /data
      volumes:
        - name: mysql-init
          persistentVolumeClaim:
            claimName: mysql-pvc-init-data
      restartPolicy: Never
