apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-host
spec:
  #progressDeadlineSeconds: 10
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 2
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: php-host
  template:
    metadata:
      labels:
        app: php-host
    spec:
      containers:
        - name: php-host
          image: akshayv1601/php:1
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1
          volumeMounts:
            - name: php-host
              mountPath: "/var/www/html/"
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_NAME
              value: login_system
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password
      volumes:
        - name: php-host
          persistentVolumeClaim:
            claimName: ebs-pvc-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  selector:
    app: php-host
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to

      # the same value as the `port` field.
      targetPort: 80
      # Optional field

      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
