apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/lib/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-pv-data
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/www/html
    type: DirectoryOrCreate
