apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-init-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
