apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmysql-deployment
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysqlcontent
        persistentVolumeClaim:
          claimName: mysql-pvc-data
      containers:
      - name: mysql
        image: akshayv1601/mysql:7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysqlcontent
          mountPath: "/var/lib/mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nfs-service
spec:
  selector:
    app: nginx
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
