kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-00e94472c13d216c3
  directoryPerms: "777"
  # gidRangeStart: "1000" #9000 # optional

# gidRangeEnd: "2000" #9000  # optional
# basePath: "/dynamic_provisioning" # optional
# subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
# ensureUniqueDirectory: "true" # optional
# reuseAccessPoint: "false" # optional
