#kubectl create secret generic mysql-cred --from-literal=MYSQL_ROOT_PASSWORD='password' --from-literal=MYSQL_DATABASE='login_system' --from-literal=MYSQL_USER='user'  --from-literal=MYSQL_PASSWORD='password1'
#Need to create secret before creting deployment 
#To use mutiple volume and you need to just add there name and same for mount volume just  have to add the name  
#For mysql it need env vaibale compulsory  so you need to specify the env variable t start the container
#even if you are using mount volume instead of env volume. 
#create config map if you want to use the Initial database setup.
#kubectl create configmap mysql-init-script --from-file=test.sql=/home/ubuntu/test/test.sql
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysqlcontent
          persistentVolumeClaim:
            claimName: mysql-pvc-data
        - name: init-script
          configMap:
            name: mysql-init-script
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          startupProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1
          volumeMounts:
            - name: mysqlcontent
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-cred
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
